# Generated by Django 6.0.3 on 2026-04-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
